import { Landmark } from "@/types/type";

export const mockLandmarks: Landmark[] = [
  {
    id: 1,
    name: "Central Park",
    description: "A large public park in Manhattan, perfect for walking and relaxation.",
    category: "Park",
    latitude: 40.7829,
    longitude: -73.9654,
    address: "New York, NY 10024",
    rating: 4.6,
    is_favorite: false,
    created_at: new Date().toISOString(),
    opening_hours: "6:00 AM - 1:00 AM",
  },
  {
    id: 2,
    name: "Statue of Liberty",
    description: "Iconic symbol of freedom and democracy, located on Liberty Island.",
    category: "Monument",
    latitude: 40.6892,
    longitude: -74.0445,
    address: "New York, NY 10004",
    rating: 4.8,
    is_favorite: false,
    created_at: new Date().toISOString(),
    opening_hours: "9:00 AM - 5:00 PM",
    entrance_fee: "$25",
  },
  {
    id: 3,
    name: "Brooklyn Bridge",
    description: "Historic suspension bridge connecting Manhattan and Brooklyn.",
    category: "Bridge",
    latitude: 40.7061,
    longitude: -73.9969,
    address: "New York, NY",
    rating: 4.7,
    is_favorite: false,
    created_at: new Date().toISOString(),
    opening_hours: "24/7",
  },
  {
    id: 4,
    name: "Times Square",
    description: "The bustling commercial intersection and entertainment center of NYC.",
    category: "Entertainment",
    latitude: 40.7580,
    longitude: -73.9855,
    address: "Manhattan, NY 10036",
    rating: 4.2,
    is_favorite: false,
    created_at: new Date().toISOString(),
    opening_hours: "24/7",
  },
  {
    id: 5,
    name: "Empire State Building",
    description: "Iconic Art Deco skyscraper with stunning city views from observation decks.",
    category: "Architecture",
    latitude: 40.7484,
    longitude: -73.9857,
    address: "350 5th Ave, New York, NY 10118",
    rating: 4.5,
    is_favorite: false,
    created_at: new Date().toISOString(),
    opening_hours: "8:00 AM - 2:00 AM",
    entrance_fee: "$44",
  },
]; 